name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101

    - name: build backend
      run: |
        cd PennywizeServer
        dotnet publish -c Release -r linux-x64

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 10.x

    - name: build frontend
      run: |
        cd pennywize-client
        npm install
        npm -g install @angular/cli
        ng build --prod
