name: TEST

on:
  push:
    branches: [ actions-test ]

defaults:
  run:
    shell: /bin/bash -eu {0}

jobs:
  test-unbound-variable:
    runs-on: ubuntu-latest

    steps:
    - name: let's see if throws
      run: |
        echo something
        echo $NONEXISTING_VAR
        echo something else